DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTU1NDc0MjYsInVzZXJJZCI6MX0.bCeMRTTkX9nGRMEy55UZE635bTcWmva-2UUtpDerPEM 